# Generated by Django 2.2.9 on 2020-01-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
