# Generated by Django 2.2.9 on 2020-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200114_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.TextField(editable=False, null=True, unique=True),
        ),
    ]
