---
# Install and configure postgres

- name: Install postgresql
  apt:
    name: ['python3-psycopg2']
    state: latest
    cache_valid_time: 3600
  become: yes
  tags: psql

- name: Run database container
  docker_container:
    name: 'psql'
    image: 'postgres:12.0-alpine'
    state: 'started'
    api_version: 3.7
    detach: yes
    keep_volumes: yes
    ports:
      - "127.0.0.1:5432:5432/tcp"
    # user:
    volumes:
      postgres_data:/var/lib/postgresql/data/pgdata
    env:
      POSTGRESQL_USER: {{db_user}}
      POSTGRESQL_PASSWORD: {{db_password}}
      POSTGRESQL_DATABASE: {{db_name}}
      PGDATA: /var/lib/postgresql/data/pgdata
  tags: psql

- set_fact:
    db_url: postgresql://{{db_user}}:{{db_password}}@localhost/{{db_name}}
  tags: psql
