---
# Rsync local app dir to remote

- name: Synchronization of source on the control machine to destination on the remote hosts
  synchronize:
    src: "{{ app_dir }}"
    dest: "{{ base_dir }}"
    rsync_opts: ['--exclude=venv', '--exclude=.vagrant', '--exclude=.idea']
  become: yes
  tags: rsync
