---
# Configure nginx web server

- name: Remove default nginx package
  apt: name=nginx state=absent
  become: yes
  tags: nginx

- name: Add APT official nginx key
  apt_key: url=https://nginx.org/keys/nginx_signing.key
  become: yes
  tags: nginx

- name: Add APT official nginx repository (mainline)
  apt_repository: repo="deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  become: yes
  tags: nginx

- name: Create nginx user
  user: name={{ user_nginx }} system=yes create_home=no group=nogroup
  become: yes
  tags: nginx

- name: Install nginx
  apt: name=nginx state=latest
  become: yes
  tags: nginx

- name: Copy local certificates
  copy: src={{ role_path }}/files/local_certs/ dest=/etc/letsencrypt/live/{{ app_domain }} force=yes
  when: env == "dev" or env == "staging"
  become: yes
  tags: nginx

- name: Copy ssl-dhparams.pem
  copy: src={{ role_path }}/files/local_certs/ssl-dhparams.pem dest=/etc/letsencrypt/ force=yes
  become: yes
  tags: nginx

- name: Remove default nginx site conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  become: yes
  tags: nginx

- name: Render nginx conf file
  template: src={{ role_path }}/templates/nginx.conf.j2 dest=/etc/nginx/conf.d/{{ app_domain }}.{{ app_name }}.conf
  become: yes
  tags: nginx

- name: Set default ACL rights to app folder for nginx
  acl: default=yes entity={{ user_nginx }} etype=user follow=no path={{ app_dir }} permissions=rX state=present
  become: yes
  tags: nginx

- name: Set ACL rights to app folder for nginx
  acl: entity={{ user_nginx }} etype=user follow=no path={{ app_dir }} permissions=rX recursive=yes state=present
  become: yes
  tags: nginx

- name: Set default ACL rights to gunicorn unix socket folder
  acl: default=yes entity={{ user_nginx }} etype=user follow=no path={{ app_dir }}/run permissions=rwX state=present
  become: yes
  tags: nginx

- name: Set ACL rights to gunicorn unix socket folder
  acl: entity={{ user_nginx }} etype=user follow=no path={{ app_dir }}/run permissions=rwX recursive=yes state=present
  become: yes
  tags: nginx

- name: Set default ACL rights to writable folders for nginx
  acl: default=yes entity={{ user_nginx }} etype=user follow=no path={{ app_dir }}/public/{{ item }} permissions=rwX
       state=present
  with_items: ['media',  'uploads']
  become: yes
  tags: nginx

- name: Set ACL rights to writable folders for nginx
  acl: entity={{ user_nginx }} etype=user follow=no path={{ app_dir }}/public/{{ item }} permissions=rwX
       recursive=yes state=present
  with_items: ['media',  'uploads']
  become: yes
  tags: nginx

- name: restart nginx
  systemd: name=nginx.service state=restarted enabled=yes
  become: yes
  tags: nginx
