---
# install certbot

- name: Add certbot repository key
  apt_repository: repo=ppa:certbot/certbot
  become: yes
  tags: certbot

- name: Install certbot
  apt: name=certbot state=latest cache_valid_time=3600
  become: yes
  tags: certbot